apiVersion: v1
kind: Service
metadata:
  name: main-web
spec:
  selector:
    app: main-web
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-web
spec:
  selector:
    matchLabels:
      app: main-web
  template:
    metadata:
      labels:
        app: main-web
    spec:
      containers:
        - name: main-web
          image: marsboy02/quipu-frontend:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
